version: '3.8'

services:
  backend:
    build:
      context: ./kamera-ai-backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - wait-for-it
    restart: always

  frontend:
    build:
      context: ./kamera-ai-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true
    restart: always

  wait-for-it:
    image: alpine:3.14
    command: /bin/sh -c "apk add --no-cache bash curl && while ! curl -s backend:5001; do sleep 1; done; echo 'Backend is ready!'"
