version: '3.8'

services:
  backend:
    build:
      context: ./kamera-ai-backend
    ports:
      - "5001:5001"
    volumes:
      - ./kamera-ai-backend:/app

  frontend:
    build:
      context: ./kamera-ai-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./kamera-ai-frontend:/app
