version: '3.8'  # You can omit this if you're getting warnings about it being obsolete

services:
  backend:
    build:
      context: ./kamera-ai-backend
    ports:
      - "5001:5001"
    volumes:
      - ./kamera-ai-backend:/app
    command: python src/fall_detection.py  # Explicitly state the command to run

  frontend:
    build:
      context: ./kamera-ai-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./kamera-ai-frontend:/app
    command: npm start  # Explicitly state the command to run
