version: '3.8'

services:
  kameraai-postgres.postgres.database.azure.com:
    image: kameraaiacr.azurecr.io/postgres:16.4  # Use the official PostgreSQL image
    environment:
      POSTGRES_USER: ${PGUSER}  # Fetch from the environment or .env
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist the database data
    ports:
      - "5432:5432"  # Expose PostgreSQL port so it is accessible outside the container
    restart: always

  pgadmin:
    image: kameraaiacr.azurecr.io/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"  # Expose pgAdmin on port 8080
    depends_on:
      - kameraai-postgres.postgres.database.azure.com
    restart: always

  wait-for-it:
    image: alpine:3.14
    command: /bin/sh -c "apk add --no-cache bash curl && while ! curl -s postgres:5432; do sleep 1; done; echo 'PostgreSQL is ready!'"

  backend:
    image: kameraaiacr.azurecr.io/kameraaiacr/frontend:a1f0b97c5c5092b0f29b2072c7961805413da261
    ports:
      - "5001:5001"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=${DATABASE_URL}  # Fetch from the environment or .env
    depends_on:
      - kameraai-postgres.postgres.database.azure.com
      - wait-for-it
    restart: always

  frontend:
    image: kameraaiacr.azurecr.io/kameraaiacr/frontend:a1f0b97c5c5092b0f29b2072c7961805413da261
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true
    restart: always

volumes:
  postgres_data:  # Named volume for persistence
