version: '3.8'

services:
  backend:
    build:
      context: ./kamera-ai-backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:THD111@postgres:5432/kamera-db
    depends_on:
      - postgres
      - wait-for-it
    restart: always

  frontend:
    build:
      context: ./kamera-ai-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true
    restart: always

  postgres:
    image: postgres:13.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: THD111
      POSTGRES_DB: kamera-db  
    volumes:
      - db_data:/var/lib/postgresql/data  
    ports:
      - "5432:5432"  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest  
    environment:
      PGADMIN_DEFAULT_EMAIL: princepaul.izuogu@stud.th-deg.de 
      PGADMIN_DEFAULT_PASSWORD: THD111
    ports:
      - "8080:80"  
    depends_on:
      - postgres  
  wait-for-it:
    image: alpine:3.14
    command: /bin/sh -c "apk add --no-cache bash curl && while ! curl -s postgres:5432; do sleep 1; done; echo 'PostgreSQL is ready!'"

volumes:
  db_data:  
