services:
  backend:
    build:
      context: ./kamera-ai-backend
    ports:
      - "5001:5001"
    volumes:
      - ./kamera-ai-backend:/app
    command: python src/fall_detection.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ./kamera-ai-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./kamera-ai-frontend:/app
    command: npm start
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
